### ISSUE TITLE
Is there any plan for ipv6 support?

### ISSUE THREAD

**Issue by dfldylan** [lwz322/luci-app-frps#4]
It looks like there is no option of listening address.
Thank you!

**Comment by lwz322** [comment]
The luci-app-frps just pass the parameter "bind-port" to frps backend. Frps already support  IPv6. 
If your frpc can't connect your frps, check your IPv6 address' accessibility. It may be caused by your openwrt router's firewall police  or upstream  router's firewall police.

My frps working well with IPv6.
![frps-netstat](https://user-images.githubusercontent.com/21271001/165960936-34445295-7b98-4fac-85bd-173e4eed5b37.jpg)

**Comment by dfldylan** [comment]
Thank you!我后来发现确实是在监听[::]地址了。我也不知道为啥我第一次用的时候只监听了0.0.0.0
